Exit on mvn fail

diff --git a/.github/workflows/mvn-release.yml b/.github/workflows/mvn-release.yml
--- a/.github/workflows/mvn-release.yml
+++ b/.github/workflows/mvn-release.yml
@@ -157,7 +157,7 @@ jobs:
       - name: Release core package
         run: |
           nexus_staging_repo="${{ needs.create-staging.outputs.staging-repo-id }}"
-          mvn clean test deploy -pl leveldb-jna-core -DstagingRepositoryId=$nexus_staging_repo
+          mvn clean test deploy -pl leveldb-jna-core -DstagingRepositoryId=$nexus_staging_repo || { (>&2 echo 'Maven deploy failed') ; exit 1; }
           if [[ -n $nexus_staging_repo ]]; then
             mvn nexus-staging:close nexus-staging:release -DstagingRepositoryId=$nexus_staging_repo
           fi
